apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      version: ">=6.6.0"
      sourceRef:
        kind: HelmRepository
        name: helm-repo-podinfo
        namespace: podinfo
  values:
    replicaCount: ${podinfoReplicas:=1}
    ui:
      color: ${podinfoColor:="#34577c"}
      message: ${podinfoMessage:="Hello from podinfo"}
    resources:
      requests:
        cpu: ${podinfoCpuRequest:=1m}
        memory: ${podinfoMemoryRequest:=8Mi}
    cache: ${podinfoRedisURL}
    redis:
      enabled: ${podinfoRedisEnabled:=false}
  