apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      version: ">=6.6.0"
      sourceRef:
        kind: HelmRepository
        name: helm-repo-podinfo
        namespace: podinfo
  interval: 5m
  values:
    replicaCount: ${podinfoReplicas:=1}
    ui:
      color: ${podinfoColor:="#34577c"}       # cue =~ "^#[0-9a-fA-F]{6}$"
      message: "${dcName} ${podinfoMessage}""
    resources:
      requests:
        cpu: ${podinfoCpuRequest:=1m}         # cue #CpuResource
        memory: ${podinfoMemoryRequest:=8Mi}  # cue #MemoryResource
    cache: ${podinfoRedisURL:=""}             # cue #URL | ""
    redis:
      enabled: ${podinfoRedisEnabled:=false}
  
  